### ISSUE TITLE
Craft cannot move because its path is obstructed!

### ISSUE THREAD

**Issue by Ricola4325** [APDevTeam/Movecraft#619]
So when I try to drive a ship on the sea and I get to a kelp, seagrass, etc... this thing shows up: "The craft cannot move because its path is obstructed! @<coordinates>, <block that is caussing this>

I've added the passthroughBlocks thing into my config, but its not working, here you have my .craft file so you can help me find out whats going on, thanks.

- Additional info:
Version: Movecraft_8.0.0-beta-2
Addons: Movecraft-Cannons_1.0.0_beta-1
Server version: 1.19.4

Config:
````
name: Brigantine
maxSize: 500
minSize: 300
allowedBlocks:
    - "#planks"
    - "#logs"
    - "#impermeable"
    - lapis_block
    - dispenser
    - note_block
    - "#beds"
    - sticky_piston
    - piston
    - piston_head
    - "#wool"
    - gold_block
    - iron_block
    - "#slabs"
    - bookshelf
    - torch
    - fire
    - "#stairs"
    - chest
    - redstone_wire
    - diamond_block
    - crafting_table
    - furnace
    - blast_furnace
    - smoker
    - "#signs"
    - "#doors"
    - ladder
    - lever
    - "#pressure_plates"
    - redstone_torch
    - redstone_wall_torch
    - "#buttons"
    - clay
    - "#fences"
    - netherrack
    - glowstone
    - cake
    - repeater
    - "#trapdoors"
    - iron_bars
    - "#fence_gates"
    - nether_brick
    - enchanting_table
    - brewing_stand
    - cauldron
    - end_stone
    - dragon_egg
    - redstone_lamp
    - ender_chest
    - tripwire_hook
    - tripwire
    - emerald_block
    - "#walls"
    - flower_pot
    - "#anvil"
    - comparator
    - daylight_detector
    - redstone_block
    - hopper
    - quartz_block
    - chiseled_quartz_block
    - quartz_pillar
    - smooth_quartz
    - activator_rail
    - dropper
    - slime_block
    - coal_block
    - bell
    - cartography_table
    - composter
    - fletching_table
    - grindstone
    - lantern
    - lectern
    - loom
    - smithing_table
    - stonecutter

forbiddenBlocks:
    - piston_head

passthroughBlocks:
    - kelp_plant
    - seagrass
    - kelp
    - tall_seagrass
    - bubble_column
canCruise: true
cruiseSkipBlocks: 2
canFly: false
sinkPercent: 99.0
overallSinkPercent: 60.0
minHeightLimit: 50
maxHeightLimit: 80
requireWaterContact: true
allowVerticalMovement: false
speed: 25.0
tryNudge: false
flyblocks:
    ["#planks", "#wooden_slabs"]:
        - 25.0
        - 70.0
    "#anvil": # anvils are OP armor, so limit it
        - 0.0
        - 1.0
    obsidian: # so is obsidian
        - 0.0
        - 1.0
    water: # so is water
        - 0.0
        - 1.0
    ["#wool"]:
        - 25.0
        - 70.0
````
